### PR TITLE
Leaflet 1.0 fixes

### PR DESCRIPTION
**Pull request by dr-itz**
Updates to make it work with Leaflet 1.0-beta. This is based on
   git://github.com/snkashis/Leaflet.label.git b1_compat
It also contains a bugfix where label positioning did not work with zoomAnimation.
Tested with Firefox 39, Chrome 44 and Safari 7.1.7.

### CODE REVIEW

**Comment by yohanboniface** [comment]
ping @jacobtoye, now that Leaflet 1.0 beta is officially out, it would be great to have plugins trunks updated, instead of everyone running their own patched fork. :)
I can give a hand if needed :)

**Comment by yohanboniface** [comment]
Same here: can you rebase to remove the dist files? :)

**Comment by yohanboniface** [comment]
It also seems to have useless file permissions changes, can you revert them and rebase? :)

**Comment by dr-itz** [comment]
Ok, will do tonight or tomorrow. I'll also pull in latest Leaflet.

**Comment by dr-itz** [comment]
Ping?

**Comment by danzel** [comment]
@dr-itz Sorry I hadn't seen this and have re-implemented it without knowing.
Check out the leaflet-master branch, this seems to work for me.
https://github.com/Leaflet/Leaflet.label/tree/leaflet-master

There are two things in this PR that aren't in there:
The z-index change. (Haven't seen any bugs related to this myself)
Listening to the 'zoomend' event (I fixed the viewreset handling which I think has fixed this).

Please re-send a PR against that branch if either of these are required. Thanks!

**Comment by dr-itz** [comment]
Hmm...the leaflet-master branch misses quite a few bits that are in master. Apart from doc changes and Bower support, it's those in the plugin itself:
* d0f4852 Add pane option (PR #81)
* af7fff8 Close open label when map is tapped on touch devices. fixes #78
* 72b56ed Disable pointer-events for the label div
* bd9f232 Enable pointer events when a label is clickable. fixes #40

Maybe you should rebase leaflet-master onto master?

**Comment by danzel** [comment]
Yeah definitely, will do, thanks!

**Comment by danzel** [comment]
Ok, leaflet-master is now redone ontop of master, old leaflet-master is now leaflet-master-old.

**Pull request closed without merging**
