### PR TITLE
Updated package.json with license info

### PR DESCRIPTION
**Pull request by gavioto**
Requiered for WebJar compatibility

### CODE REVIEW

**Comment by gavioto** [comment]
Updated json for webjar compatibility

**Comment by tmcw** [comment]
Thanks!

**Comment by gavioto** [comment]
This solves issue #137

**Comment by gavioto** [comment]
Please, could you create a new tag for this revision. bower webjar needs a tag to work. May be something like 0.2.2-beta... Thanks

**Pull request merged**
