### PR TITLE
fixes module loading issues

### PR DESCRIPTION
**Pull request by harrytruong**
## See issue #116 "package.json missing dependencies":

`package.json` is missing the `dependencies` declaration for leaflet. This breaks loading leaflet.label in a non-browser tools (i.e., `npm install`).

``` js
 {
    "name": "leaflet.label",
    "version": "0.2.1",
    "description": "Labels for leaflet maps",
+   "dependencies": {
+       "leaflet": "~0.7.0"
+   },
    "devDependencies": {
        "jshint": "~2.1.4",
        "uglify-js": "~2.3.6"
    },
    "main": "dist/leaflet.label.js",
       ...
}
```

---
## See issue #115 "AMD & CommonJS (Node) Support"

`build.js` (used by `Jakefile.js`) loads leaflet (`L`) by referencing `window.L`. 

Rather than relying on browser globals (which breaks for non-browser environments), can we implement AMD / CommonJS, and use browser global as a fallback?

See https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js

``` js
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['leaflet'], factory);
    } else if (typeof exports === 'object') {
        // Node/CommonJS
        module.exports = factory(require('leaflet'));
    } else {
        // Browser globals
        factory(L);
    }
}(function (L) {

    // leaflet plugin code goes here
    L.labelVersion = '0.2.1';

    // ... etc ...


}));
```

### CODE REVIEW

**Comment by harrytruong** [comment]
Pinging @jacobtoye and @danzel.

This PR is related to https://github.com/Leaflet/Leaflet.label/pull/34, where the `package.json` file was originally introduced.

I hope you guys will look into merging this. With these changes, `npm install` will work properly, and will also enable other npm-based package managers (i.e., [jspm](http://jspm.io/), which is the ES6 future!)

**Comment by zakjan** [comment]
+1 please, merge this

**Comment by digitalkaoz** [comment]
a merge would be nice :)

**Comment by harrytruong** [comment]
Sorry, this PR is super old at this point, so I'm just closing it.

**Pull request closed without merging**
